name: Deploy Frontend to Azure

on:
  push:
    branches:
      - main
    paths:
      - 'classroom-booking/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      working-directory: classroom-booking
      run: npm install

    - name: Build project
      working-directory: classroom-booking
      run: npm run build

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: classroom-booking-frontend
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_FRONTEND }}
        package: package: classroom-booking/dist

